## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('switched-ethernet-packet-socket', ['switched-ethernet', 'internet'])
    obj.source = 'switched-ethernet-packet-socket.cc'
